[theme]
primaryColor = "#003366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F5F8"
textColor = "#1A1A1A"
font = "serif"

[server]
maxUploadSize = 25

[browser]
gatherUsageStats = false
